### PR TITLE
doc(release): Explains how to maintain the stable branch.

### PR DESCRIPTION
**Pull request by GerardPaligot**
Updates Checklist file to explain how to maintain the stable branch
and updates CONTRIBUTING file to explain at the community how to
create a pull request which contains a bug fix of the current
release.

Closes #203

### CODE REVIEW

**Comment by boeserwolf91** [comment]
@GerardPaligot Does the part about the version number explanation exist already? You wrote about it in #203 "What is the meaning of each digit in the version X.Y.Z?".

**Comment by GerardPaligot** [comment]
Thanks @boeserwolf91. The PR is updated: https://github.com/INRIA/spoon/pull/395

This PR is on my fork and used to test a new continuous-integration made by INRIA. :)

**Comment by boeserwolf91** [comment]
Oh I commented on your fork. I didn't notice that. I found it with the link on the issue. :smile: 
But I'm really glad to see that change. I hope it'll be used if necessary. Thanks for all (especially) your work always! :+1:

**Comment by GerardPaligot** [comment]
> But I'm really glad to see that change. I hope it'll be used if necessary.

I hope too. I'll ensure that it is used.

> Thanks for all (especially) your work always! :+1:

You're welcome! :)

**Pull request closed without merging**
