### PR TITLE
fix(stack): fix invalid field name in CtExexuable#setBody

### PR DESCRIPTION
**Pull request by tdurieux**

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Well seen.

**Comment by GerardPaligot** [comment]
Why the last commit is necessary? Can you add too a commit to fix the Java version?

**Comment by tdurieux** [comment]
My mistake, It was not the good branch.

**Comment by GerardPaligot** [comment]
You have another branch with a stack? :)

**Comment by tdurieux** [comment]
I try to create the sniper feature but for some action the context does not contains the element that we have to reprint.

Example: update the modifier of a method -> the context contains only the set of modifier but I need the method in order to reprint the new modifiers...

You will see the next PR

**Comment by GerardPaligot** [comment]
Ok, can't wait to see it. :)

I merge this one or I should wait?

**Comment by tdurieux** [comment]
Merge the other PR #28  then I will rebase this one

**Comment by GerardPaligot** [comment]
Merged. Rebase this one to see if Travis is ok or not.

**Comment by tdurieux** [comment]
The stack is horrible to debug because the intellij debugger call some method that add elements in the stack. 
Every time you stop the execution the stack gets bigger... (maybe intellij call the clone method in order to not change the state of the program)

**Comment by GerardPaligot** [comment]
Really? That's weird.

**Comment by tdurieux** [comment]
Travis likes this PR :+1:

**Comment by GerardPaligot** [comment]
Nice.

**Pull request merged**
